# Generated by Django 3.2 on 2024-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_utilization', models.FloatField(blank=True, null=True)),
                ('memory_utilization', models.FloatField(blank=True, null=True)),
                ('disk_utilization', models.FloatField(blank=True, null=True)),
                ('network_in', models.FloatField(blank=True, null=True)),
                ('network_out', models.FloatField(blank=True, null=True)),
                ('cpu_credit_balance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
